using RELY_API.Models;
using RELY_API.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;

namespace RELY_API.Controllers
{
    [CustomExceptionFilter]
    public class LFSItemTemplatesController : ApiController
    {
        private RELYDevDbEntities db = new RELYDevDbEntities();

        // GET: api/LFSItemTemplates? CompanyCode = DE
        //Method to Get Data in Grid
        //SG commented this code as table is no more there

      /*  public IHttpActionResult GetLFSItemTemplatesByCompanyCode(string CompanyCode, string UserName, string WorkFlow)
        {
            var xx = (from aa in db.LFSItemTemplates.Where(p => p.CompanyCode == CompanyCode)
                      select new
                      {
                          aa.Id,
                          aa.CompanyCode,
                          aa.Name,
                          aa.HTMLText
                      }).OrderBy(p => p.Name);
            return Ok(xx);
        }

        // POST: api/LFSItemTemplates
        //Method to Post Data from app to db
        [ResponseType(typeof(LFSItemTemplate))]
        public async Task<IHttpActionResult> PostLFSItemTemplates(LFSItemTemplate LFSItemTemplate,string UserName,string WorkFlow)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "CREATE", "ItemTemplate")));
            }

            try
            {
                if(db.LFSItemTemplates.Where(p=>p.Id==LFSItemTemplate.Id).Where(p=>p.CompanyCode==LFSItemTemplate.CompanyCode).Count() > 0)
                {
                    db.Entry(LFSItemTemplate).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
                else
                {
                    LFSItemTemplate.Id = 0;//To override the Id generated by grid
                    db.LFSItemTemplates.Add(LFSItemTemplate);
                    await db.SaveChangesAsync();
                }
            }
            catch(DbEntityValidationException dbex)
            {
                var errorMessage = Globals.GetEntityValidationErrorMessage(dbex);
                throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, errorMessage));//type 2 error
            }
            catch(Exception ex)
            {
                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry.
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;//This exception will be handled in FilterConfig's CustomHandler
                }
            }

            return CreatedAtRoute("DefaultApi", new { id = LFSItemTemplate.Id }, LFSItemTemplate);
        }

        // GET: api/LFSItemTemplates?CompanyCode=DE&Name=System1
        //Method to Get Requested Data by user for Edit

        [ResponseType(typeof(LFSItemTemplate))]
        public async Task<IHttpActionResult> GetLFSItemTemplates(string CompanyCode,string Name, string UserName, string WorkFlow)
        {
            var LFSItemTemplate = db.LFSItemTemplates.Where(p => p.CompanyCode == CompanyCode && p.Name == Name).Select(x =>
                                        new
                                        {
                                            x.Id,
                                            x.CompanyCode,
                                            x.Name,
                                            x.HTMLText
                                        }).First();
            if(LFSItemTemplate==null)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage, "ItemTemplate")));
            }

            return Ok(LFSItemTemplate);
        }

        // PUT: api/LFSItemTemplates?CompanyCode=DE&Name=System(updated name)
        //Method to update Requested Data by User in db

        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutLFSItemTemplates(string CompanyCode, string Name, LFSItemTemplate LFSItemTemplate, string UserName, string WorkFlow)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "UPDATE", "ITEMTEMPLATE")));
            }

            if (!LFSItemTemplatesExists(CompanyCode) && !LFSItemTemplatesExists(Name))
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage, "ITEMTEMPLATE")));
            }

            if (CompanyCode != LFSItemTemplate.CompanyCode && Name != LFSItemTemplate.Name)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "UPDATE", "ITEMTEMPLATE")));
            }
            try
            {
                db.Entry(LFSItemTemplate).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            catch (DbEntityValidationException dbex)
            {

                var errorMessage = Globals.GetEntityValidationErrorMessage(dbex);
                throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, errorMessage));//type 2 error
            }
            catch (Exception ex)
            {

                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry.
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;//This exception will be handled in FilterConfig's CustomHandler
                }
            }

            // return StatusCode(HttpStatusCode.NoContent);
            return Ok(LFSItemTemplate);
        }

        // Delete: api/LFSQuestionBank?id
        [ResponseType(typeof(LFSItemTemplate))]
        public async Task<IHttpActionResult> DeleteLFSItemTemplates(int id, string UserName, string WorkFlow)
        {
            LFSItemTemplate LFSItemTemplate = await db.LFSItemTemplates.FindAsync(id);
            if (LFSItemTemplate == null)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage, "Item Template")));
            }

            try
            {
                db.LFSItemTemplates.Remove(LFSItemTemplate);
                await db.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry. 
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;
                }
            }
            return Ok(LFSItemTemplate);
        }
        private bool LFSItemTemplatesExists(string CompanyCode)
        {
            return db.LFSItemTemplates.Count(e => e.CompanyCode == CompanyCode) > 0;
        }

        private string GetCustomizedErrorMessage(Exception ex)
        {
            //Convert the exception to SqlException to get the error message returned by database.
            var SqEx = ex.GetBaseException() as SqlException;
            //Depending upon the constraint failed return appropriate error message
            if (SqEx.Message.IndexOf("FK_LFSItemTemplates_LFSItemTypes_TemplateId", StringComparison.OrdinalIgnoreCase) >= 0)
                return (string.Format(Globals.CanNotUpdateDeleteErrorMessage, "ITEM TEMPLATE", "ITEM TYPES"));
            else if
                (SqEx.Message.IndexOf("UQ_LFSItemTemplates_CompanyCode_Name", StringComparison.OrdinalIgnoreCase) >= 0)
                return (string.Format(Globals.CannotInsertDuplicateErrorMessage, "ITEM TEMPLATE"));
            else
            {
                //Something else failed return original error message as retrieved from database
                //Add complete Url in description
                var UserName = "";//System.Web.HttpContext.Current.Session["UserName"] as string;
                string UrlString = Convert.ToString(Request.RequestUri.AbsolutePath);
                var ErrorDesc = "";
                var Desc = Request.GetQueryNameValuePairs().ToDictionary(x => x.Key, x => x.Value);
                if (Desc.Count() > 0)
                    ErrorDesc = string.Join(",", Desc);
                string[] s = Request.RequestUri.AbsolutePath.Split('/');//This array will provide controller name at 2nd and action name at 3 rd index position
                db.SpLogError("RELY-API", s[2], s[3], SqEx.Message, UserName, "Type2", ErrorDesc, "resolution", "L2Admin", "field", 0, "New");
                return Globals.SomethingElseFailedInDBErrorMessage;
            }
        }*/
    }
}
