using RELY_API.Models;
using RELY_API.Utilities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Validation;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;

namespace RELY_API.Controllers
{
    [CustomExceptionFilter]
    public class LFSQuestionBankController : ApiController
    {
        private RELYDevDbEntities db = new RELYDevDbEntities();

        // GET: api/LFSQuestionBank? CompanyCode = DE
        //Method to Get Data in Grid

        public IHttpActionResult GetLFSQuestionBanksByCompanyCode(string CompanyCode, string UserName, string WorkFlow)
        {
            var xx = (from aa in db.LFSQuestionBanks.Where(p => p.CompanyCode == CompanyCode)
                      select new
                      {
                          aa.Id,
                          aa.CompanyCode,
                          aa.ItemTypeId,
                          aa.QuestionCode,
                          aa.QuestionName,
                          aa.Comments,
                          aa.ReadableName,
                          aa.QuestionText,
                          aa.ToolTip,
                          aa.VGAPReference,
                          aa.IFRSReference,
                          aa.IsActive,
                          aa.CreatedById,
                          aa.CreatedDateTime,
                          aa.UpdatedById,
                          aa.UpdatedDateTime
                      }).OrderBy(p=> p.QuestionName);
            return Ok(xx);
        }
        public IHttpActionResult GetQuestionDetailsForScnDemand(string QuestionCode , string CompanyCode)
        {
            var qry = "select  aa.Id,aa.QuestionCode,aa.QuestionText,bb.Response from LFSQuestionBank aa left outer join LFSResponses bb on aa.QuestionCode = bb.QuestionCode where aa.QuestionCode = {0} and aa.CompanyCode = {1}";
            var result = db.Database.SqlQuery<QuestionDetailsForDemandViewModel>(qry, QuestionCode,CompanyCode).FirstOrDefault();
            return Ok(result);
        }

        public IHttpActionResult GetLFSQuestionBank()
        {
            var xx = (from aa in db.LFSQuestionBanks
                      join yy in db.LFSItemTypes on aa.ItemTypeId equals yy.Id
                      select new
                      {
                          aa.Id,
                          aa.CompanyCode,
                          aa.ItemTypeId,
                          aa.QuestionCode,
                          aa.QuestionName,
                          aa.Comments,

                          aa.ReadableName,
                          aa.QuestionText,
                          aa.ToolTip,
                          aa.VGAPReference,
                          aa.IFRSReference,
                          aa.IsActive,
                          aa.InternalNotes,
                          aa.CreatedById,
                          aa.CreatedDateTime,
                          aa.UpdatedById,
                          aa.UpdatedDateTime,
                         yy.Name
                          
                      }).OrderByDescending(p => p.Id);
            return Ok(xx);
        }
        // POST: api/LFSQuestionBank
        //Method to Post Data from app to db
        [ResponseType(typeof(LFSQuestionBank))]
        public async Task<IHttpActionResult> PostLFSQuestionBanks(LFSQuestionBank LFSQuestionBank, string UserName, string WorkFlow)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "CREATE","QuestionBank")));
            }

            try
            {
                if (db.LFSQuestionBanks.Where(p => p.Id == LFSQuestionBank.Id).Where(p => p.CompanyCode == LFSQuestionBank.CompanyCode).Count() > 0)
                {
                    db.Entry(LFSQuestionBank).State = EntityState.Modified;
                    await db.SaveChangesAsync();
                }
                else
                {
                    LFSQuestionBank.Id = 0;//To override the Id generated by grid
                    db.LFSQuestionBanks.Add(LFSQuestionBank);
                    await db.SaveChangesAsync();
                }
            }
            catch (DbEntityValidationException dbex)
            {

                var errorMessage = Globals.GetEntityValidationErrorMessage(dbex);
                throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, errorMessage));//type 2 error
            }
            catch (Exception ex)
            {

                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry.
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;//This exception will be handled in FilterConfig's CustomHandler
                }
            }
            return CreatedAtRoute("DefaultApi", new { id = LFSQuestionBank.Id }, LFSQuestionBank);
        }

        [HttpPost]
        [ResponseType(typeof(LFSQuestionBank))]
        public async Task<IHttpActionResult> PostLFSQuestionBank(List<LFSQuestionBank> LFSQuestionBank, string UserName, string WorkFlow)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "CREATE", "LFSQuestionBank")));
            }
            using (var transaction = db.Database.BeginTransaction())
            {
                try
                {
                    int LoggedInUserId = 0;
                    foreach (var model in LFSQuestionBank)
                    {
                        if (model.Id == 0)//add only when new record is there to insert.
                            db.LFSQuestionBanks.Add(model);
                        LoggedInUserId = model.UpdatedById;
                        await db.SaveChangesAsync();
                    }

                }
                catch (DbEntityValidationException dbex)
                {
                    transaction.Rollback();
                    var errorMessage = Globals.GetEntityValidationErrorMessage(dbex);
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, errorMessage));//type 2 error
                }
                catch (Exception ex)
                {
                    transaction.Rollback();
                    if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                    {
                        //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry.
                        throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                    }
                    else
                    {
                        throw ex;//This exception will be handled in FilterConfig's CustomHandler
                    }
                }

                transaction.Commit();
            }

            return Ok();
        }

        // GET: api/LFSQuestionBank?CompanyCode=DE&QuestionName=System1
        //Method to Get Requested Data by user for Edit
        [ResponseType(typeof(LFSQuestionBank))]
        public async Task<IHttpActionResult> GetLFSQuestionBanks(string CompanyCode,string QuestionName, string UserName, string WorkFlow)
        {
            var LFSQuestionBank = db.LFSQuestionBanks.Where(p => p.CompanyCode == CompanyCode && p.QuestionName == QuestionName).Select(x =>
                                      new
                                      {
                                          x.Id,
                                          x.CompanyCode,
                                          x.ItemTypeId,
                                          x.QuestionCode,
                                          x.QuestionName,
                                          x.Comments,
                                          x.ReadableName,
                                          x.QuestionText,
                                          x.ToolTip,
                                          x.VGAPReference,
                                          x.IFRSReference,
                                          x.IsActive,
                                          x.CreatedById,
                                          x.CreatedDateTime,
                                          x.UpdatedById,
                                          x.UpdatedDateTime
                                      }).First();
            if(LFSQuestionBank==null)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage,"QuestionBank")));
            }

            return Ok(LFSQuestionBank);
        }

        // PUT: api/LFSQuestionBank?CompanyCode=DE&QuestionName=System(updated name)
        //Method to update Requested Data by User in db
        [ResponseType(typeof(void))]
        public async Task<IHttpActionResult> PutLFSQuestionBanks(string CompanyCode, string QuestionName, LFSQuestionBank LFSQuestionBank, string UserName, string WorkFlow)
        {
            if (!ModelState.IsValid)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "UPDATE", "QUESTIONBANK")));
            }

            if (!LFSQuestionBankExists(CompanyCode) && !LFSQuestionBankExists(QuestionName))
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage, "QUESTIONBANK")));
            }

            if (CompanyCode != LFSQuestionBank.CompanyCode && QuestionName != LFSQuestionBank.QuestionName)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.BadRequest, string.Format(Globals.BadRequestErrorMessage, "UPDATE", "QUESTIONBANK")));
            }
            try
            {
                db.Entry(LFSQuestionBank).State = EntityState.Modified;
                await db.SaveChangesAsync();
            }
            catch (DbEntityValidationException dbex)
            {

                var errorMessage = Globals.GetEntityValidationErrorMessage(dbex);
                throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, errorMessage));//type 2 error
            }
            catch (Exception ex)
            {

                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry.
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;//This exception will be handled in FilterConfig's CustomHandler
                }
            }

            // return StatusCode(HttpStatusCode.NoContent);
            return Ok(LFSQuestionBank);
        }

        // Delete: api/LFSQuestionBank?id
        [ResponseType(typeof(LFSQuestionBank))]
        public async Task<IHttpActionResult> DeleteLFSQuestionBanks(int id, string UserName, string WorkFlow)
        {
            LFSQuestionBank LFSQuestionBank = await db.LFSQuestionBanks.FindAsync(id);
            if (LFSQuestionBank == null)
            {
                throw new HttpResponseException(Request.CreateErrorResponse(HttpStatusCode.NotFound, string.Format(Globals.NotFoundErrorMessage, "Question Bank")));
            }

            try
            {
                db.LFSQuestionBanks.Remove(LFSQuestionBank);
                await db.SaveChangesAsync();

            }
            catch (Exception ex)
            {
                if (ex.GetBaseException().GetType() == typeof(SqlException))//check for exception type
                {
                    //Throw this as HttpResponse Exception to let user know about the mistakes they made, correct them and retry. 
                    throw new HttpResponseException(Request.CreateErrorResponse((HttpStatusCode)Globals.ExceptionType.Type2, GetCustomizedErrorMessage(ex)));//type 2 error
                }
                else
                {
                    throw ex;
                }
            }
            return Ok(LFSQuestionBank);
        }
        private bool LFSQuestionBankExists(string CompanyCode)
        {
            return db.LFSQuestionBanks.Count(e => e.CompanyCode == CompanyCode) > 0;
        }

        private string GetCustomizedErrorMessage(Exception ex)
        {
            //Convert the exception to SqlException to get the error message returned by database.
            var SqEx = ex.GetBaseException() as SqlException;
            //Depending upon the constraint failed return appropriate error message
            //if (SqEx.Message.IndexOf("FK_LFSQuestionBank_LFSAnswerBank_QuestionId", StringComparison.OrdinalIgnoreCase) >= 0)
            //    return (string.Format(Globals.CanNotUpdateDeleteErrorMessage, "QUESTION BANK", "ANSWERS"));
            //else 
            if
                (SqEx.Message.IndexOf("UQ_LFSQuestionBank_CompanyCode_QuestionCode", StringComparison.OrdinalIgnoreCase) >= 0)
                return (string.Format(Globals.CannotInsertDuplicateErrorMessage, "QUESTION BANK"));
            else
            {
                //Something else failed return original error message as retrieved from database
                //Add complete Url in description
                var UserName = "";//System.Web.HttpContext.Current.Session["UserName"] as string;
                string UrlString = Convert.ToString(Request.RequestUri.AbsolutePath);
                var ErrorDesc = "";
                var Desc = Request.GetQueryNameValuePairs().ToDictionary(x => x.Key, x => x.Value);
                if (Desc.Count() > 0)
                    ErrorDesc = string.Join(",", Desc);
                string[] s = Request.RequestUri.AbsolutePath.Split('/');//This array will provide controller name at 2nd and action name at 3 rd index position
                //db.SpLogError("RELY-API", s[2], s[3], SqEx.Message, UserName, "Type2", ErrorDesc, "resolution", "L2Admin", "field", 0, "New");
                //return Globals.SomethingElseFailedInDBErrorMessage;

             ObjectParameter Result = new ObjectParameter("Result", typeof(int)); //return parameter is declared
                db.SpLogError("RELY-API", s[2], s[3], SqEx.Message, UserName, "Type2", ErrorDesc, "resolution", "L2Admin", "field", 0, "New", Result).FirstOrDefault();
                int errorid = (int)Result.Value; //getting value of output parameter
                //return Globals.SomethingElseFailedInDBErrorMessage;
                return (string.Format(Globals.SomethingElseFailedInDBErrorMessage, errorid));
            }
        }

    }
}
