using RELY_APP.Utilities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace RELY_APP.ViewModel
{
    public class LFSResponsViewModel
    {
        [Display(Name = "Id")]
        [Required(ErrorMessage = "Id is required")]
        public int Id { get; set; }

        [Display(Name = "SectionItemId")]
        [Required(ErrorMessage = "Section ItemId is required")]
        public int SectionItemId { get; set; }
        
        [RestrictSpecialChar]
        [Display(Name = "IsReponseAutoGenerated")]
        [Required(ErrorMessage = "IsReponseAutoGenerated  is required")]
        public bool IsReponseAutoGenerated { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Response")]
        [Required(ErrorMessage = "Response  is required")]
        public string Response { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Conclusion Text")]
        [Required(ErrorMessage = "Conclusion Text  is required")]
        public string ConclusionText { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Comments")]
        [Required(ErrorMessage = "Comments  is required")]
        [MaxLength(4000, ErrorMessage = " Answer Option can be maximum 4000 characters")]
        public string Comments { get; set; }

        [Display(Name = "Created By Id")]
        [Required(ErrorMessage = "CreatedById is required")]
        public int CreatedById { get; set; }


        [Display(Name = "Created Date Time")]
        [Required(ErrorMessage = "Created Date Time is Required.")]
        public DateTime CreatedDateTime { get; set; }

        [Display(Name = "Updated By Id")]
        [Required(ErrorMessage = "UpdatedById is required")]
        public int UpdatedById { get; set; }


        [Display(Name = "Updated Date Time")]
        [Required(ErrorMessage = "Updated Date Time is Required.")]
        public DateTime UpdatedDateTime { get; set; }

        [Display(Name = "Entity Id")]
        [Required(ErrorMessage = "Entity Id is required")]
        public int EntityId { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Entity Type")]
        [Required(ErrorMessage = "Entity Type  is required")]
        [MaxLength(255, ErrorMessage = " Entity Type can be maximum 255 characters")]
        public string EntityType { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Object Type")]
        [Required(ErrorMessage = "Object Type  is required")]
        [MaxLength(255, ErrorMessage = " Object Type can be maximum 255 characters")]
        public string ObjectType { get; set; }

        [RestrictSpecialChar]
        [Display(Name = "Question Code")]
        [Required(ErrorMessage = "Question Code is required")]
        [MaxLength(20, ErrorMessage = " Chapter Code can be maximum 20 characters")]
        public string QuestionCode { get; set; }

        //SS added two columns for Acc Scenario Change Grid
        public string AnswerOption { get; set; }
        public string MemoText { get; set; }
    }
}