//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GErrorLog
    {
        public int Id { get; set; }
        public System.DateTime ErrorDateTime { get; set; }
        public string SourceProject { get; set; }
        public string Controller { get; set; }
        public string Method { get; set; }
        public string StackTrace { get; set; }
        public string UserName { get; set; }
        public string ErrorType { get; set; }
        public string ErrorDescription { get; set; }
        public string Resolution { get; set; }
        public string ErrorOwner { get; set; }
        public string FieldName { get; set; }
        public Nullable<int> BatchNumber { get; set; }
        public string Status { get; set; }
    }
}
