//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GMenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GMenu()
        {
            this.GMenus1 = new HashSet<GMenu>();
            this.MMenuRoles = new HashSet<MMenuRole>();
            this.MMenusAuthorizableObjects = new HashSet<MMenusAuthorizableObject>();
        }
    
        public int Id { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string MenuName { get; set; }
        public string MenuURL { get; set; }
        public int OrdinalPosition { get; set; }
        public string CompanyCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GMenu> GMenus1 { get; set; }
        public virtual GMenu GMenu1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMenuRole> MMenuRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MMenusAuthorizableObject> MMenusAuthorizableObjects { get; set; }
    }
}
