//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LAudit
    {
        public int Id { get; set; }
        public string RelyProcessName { get; set; }
        public string VFProcessName { get; set; }
        public string ControlCode { get; set; }
        public string ControlDescription { get; set; }
        public string Action { get; set; }
        public string ActionType { get; set; }
        public int ActionedById { get; set; }
        public Nullable<int> ActionedByRoleId { get; set; }
        public System.DateTime ActionDateTime { get; set; }
        public string OldStatus { get; set; }
        public string NewStatus { get; set; }
        public string EntityType { get; set; }
        public int EntityId { get; set; }
        public string EntityName { get; set; }
        public Nullable<int> WorkFlowId { get; set; }
        public string CompanyCode { get; set; }
        public string Comments { get; set; }
        public Nullable<int> StepId { get; set; }
        public string ActionLabel { get; set; }
        public Nullable<int> SupportingDocumentId { get; set; }
    
        public virtual LRole LRole { get; set; }
        public virtual LSupportingDocument LSupportingDocument { get; set; }
        public virtual LUser LUser { get; set; }
        public virtual RWorkFlow RWorkFlow { get; set; }
        public virtual WStep WStep { get; set; }
    }
}
