//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LCompanySpecificColumn
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string TableName { get; set; }
        public string ColumnName { get; set; }
        public string Label { get; set; }
        public bool DisplayOnForms { get; set; }
        public int OrdinalPosition { get; set; }
        public bool IsMandatory { get; set; }
        public string ExportHeader { get; set; }
        public Nullable<int> DropDownId { get; set; }
        public string DefaultValue { get; set; }
        public bool IsReportParameter { get; set; }
        public Nullable<int> ReportParameterOrdinal { get; set; }
        public string DataType { get; set; }
        public Nullable<int> MaximumLength { get; set; }
        public Nullable<int> DigitsAfterDecimal { get; set; }
        public bool IsMultiline { get; set; }
        public Nullable<int> ReferenceTypeId { get; set; }
        public string SelecterType { get; set; }
        public bool DisplayInGrid { get; set; }
        public bool AuditEnabled { get; set; }
    
        public virtual LDropDown LDropDown { get; set; }
        public virtual LReferenceType LReferenceType { get; set; }
    }
}
