//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFSAnswerBank
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string QuestionCode { get; set; }
        public string AnswerOption { get; set; }
        public string MemoText { get; set; }
        public string Comments { get; set; }
        public int CreatedById { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string InternalNotes { get; set; }
        public string ScenarioCategory { get; set; }
        public string ScenarioTrigger { get; set; }
    
        public virtual LUser LUser { get; set; }
        public virtual LUser LUser1 { get; set; }
    }
}
