//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFSAccountingMemo
    {
        public string EntityType { get; set; }
        public int EntityId { get; set; }
        public Nullable<int> SurveyId { get; set; }
        public string ChapterCode { get; set; }
        public string SectionCode { get; set; }
        public Nullable<int> SectionItemId { get; set; }
        public string QuestionCode { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ItemType { get; set; }
        public Nullable<int> MemoItemOrdinal { get; set; }
        public string MemoCol1 { get; set; }
        public string MemoCol2 { get; set; }
        public string Memocol3 { get; set; }
        public string Memocol4 { get; set; }
        public string Memocol5 { get; set; }
        public string Memocol6 { get; set; }
        public string Memocol7 { get; set; }
        public string Memocol8 { get; set; }
        public string Memocol9 { get; set; }
        public string Memocol10 { get; set; }
        public string Memocol11 { get; set; }
        public string Memocol12 { get; set; }
        public string Memocol13 { get; set; }
        public string Memocol14 { get; set; }
        public string Memocol15 { get; set; }
        public string QuestionName { get; set; }
        public string OutputFormat { get; set; }
        public int ExcelRowHeight { get; set; }
    }
}
