using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace RELY_API.Models
{
    public class LFSSectionItemsViewModel
    {
        public int Id { get; set; }

        public int SurveyId { get; set; }
        public string ToolTip { get; set; }
        public bool IsQuestion { get; set; }
        public string Response { get; set; }
        public string ChapterCode { get; set; }

        public string SectionCode { get; set; }

        public string QuestionCode { get; set; }

        public string ItemTypeName { get; set; }
        public string SectionName { get; set; }
        public string SectionNumber { get; set; }


        public int ItemTypeId { get; set; }

        public string ItemText { get; set; }

        public int Ordinal { get; set; }

        public int NestingLevel { get; set; }

        public bool IsResponseMandatory { get; set; }

        public bool IsReponseAutoGenerated { get; set; }

        public string ShowOnQuestionCode { get; set; }

        public string ShowOnAnswerOption { get; set; }

        public string SumOfQuestions { get; set; }

        public string Operator { get; set; }

        public Nullable<int> SumValue { get; set; }

        public bool AutomatedResponseValue { get; set; }

        public string RelatedQuestionCode { get; set; }

        public bool ShowOnAccountingMemo { get; set; }

        public int CreatedById { get; set; }


        public DateTime CreatedDateTime { get; set; }

        public int UpdatedById { get; set; }
        public DateTime UpdatedDateTime { get; set; }
    }
}