//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LFSTable
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string TableCode { get; set; }
        public string TableTitle { get; set; }
        public int NoOfCols { get; set; }
        public int NoOfRows { get; set; }
    }
}
