//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LNotification
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string Type { get; set; }
        public string Description { get; set; }
        public Nullable<int> RemindAfterDays { get; set; }
        public int TemplateId { get; set; }
        public Nullable<int> LandingStepId { get; set; }
        public Nullable<int> RecipientRoleId { get; set; }
        public string SkipFuntion { get; set; }
        public Nullable<int> OriginatingStepId { get; set; }
    
        public virtual LEmailTemplate LEmailTemplate { get; set; }
        public virtual WStep WStep { get; set; }
        public virtual LRole LRole { get; set; }
    }
}
