//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LReconColumnMapping
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int FileFormatId { get; set; }
        public string ColumnName { get; set; }
        public string Label { get; set; }
        public bool DisplayOnForm { get; set; }
        public Nullable<int> OrdinalPosition { get; set; }
        public bool IsProductCodeColumn { get; set; }
    
        public virtual LReconFileFormat LReconFileFormat { get; set; }
    }
}
