//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LReconFileFormat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LReconFileFormat()
        {
            this.LReconBatches = new HashSet<LReconBatch>();
            this.LReconColumnMappings = new HashSet<LReconColumnMapping>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int SysCatId { get; set; }
        public string FormatName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconBatch> LReconBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconColumnMapping> LReconColumnMappings { get; set; }
        public virtual RSysCat RSysCat { get; set; }
    }
}
