//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LReconBatch
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int FileFormatId { get; set; }
        public int BatchNumber { get; set; }
        public string SourceFileName { get; set; }
        public string UploadMode { get; set; }
        public int CreatedById { get; set; }
        public Nullable<System.DateTime> CreatedDateTime { get; set; }
        public int UpdatedById { get; set; }
        public Nullable<System.DateTime> UpdatedDateTime { get; set; }
    
        public virtual LReconFileFormat LReconFileFormat { get; set; }
        public virtual LUser LUser { get; set; }
        public virtual LUser LUser1 { get; set; }
    }
}
