//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LScenarioDemand
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public Nullable<int> BusinessAreaId { get; set; }
        public int ProductId { get; set; }
        public Nullable<int> RequestId { get; set; }
        public string QuestionCode { get; set; }
        public string ScenarioDescription { get; set; }
        public string Standards { get; set; }
        public string CommentInbound { get; set; }
        public string Arguments { get; set; }
        public bool Inception { get; set; }
        public bool AddGoodService { get; set; }
        public bool Fulfilment { get; set; }
        public bool PriceChange { get; set; }
        public bool RemoveGoodService { get; set; }
        public bool Termination { get; set; }
        public bool BillRunReconciliation { get; set; }
        public bool ContractFreeze { get; set; }
        public bool UsageFulfillment { get; set; }
        public bool UpdateSyncCopa { get; set; }
        public int CreatedById { get; set; }
        public int Version { get; set; }
        public string Status { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFComments { get; set; }
        public Nullable<int> WFRequesterId { get; set; }
        public Nullable<int> WFAnalystId { get; set; }
        public Nullable<int> WFManagerId { get; set; }
        public Nullable<int> WFCurrentOwnerId { get; set; }
        public Nullable<int> WFRequesterRoleId { get; set; }
        public Nullable<System.DateTime> WFStatusDateTime { get; set; }
        public Nullable<System.DateTime> WFIsReadyDateTime { get; set; }
        public Nullable<System.DateTime> ImplementationDate { get; set; }
    
        public virtual LDropDownValue LDropDownValue { get; set; }
        public virtual LProduct LProduct { get; set; }
        public virtual LRequest LRequest { get; set; }
        public virtual LRole LRole { get; set; }
        public virtual LUser LUser { get; set; }
        public virtual LUser LUser1 { get; set; }
        public virtual LUser LUser2 { get; set; }
        public virtual LUser LUser3 { get; set; }
        public virtual LUser LUser4 { get; set; }
        public virtual LUser LUser5 { get; set; }
    }
}
