//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LUser()
        {
            this.FlexTables = new HashSet<FlexTable>();
            this.GCopaDimensions = new HashSet<GCopaDimension>();
            this.GCopaDimensions1 = new HashSet<GCopaDimension>();
            this.GGlobalPobs = new HashSet<GGlobalPob>();
            this.LAccountingScenarios = new HashSet<LAccountingScenario>();
            this.LAccountingScenarios1 = new HashSet<LAccountingScenario>();
            this.LAccountingScenarios2 = new HashSet<LAccountingScenario>();
            this.LAccountingScenarios3 = new HashSet<LAccountingScenario>();
            this.LAccountingScenarios4 = new HashSet<LAccountingScenario>();
            this.LAccountingScenarios5 = new HashSet<LAccountingScenario>();
            this.LAudits = new HashSet<LAudit>();
            this.LEmailBuckets = new HashSet<LEmailBucket>();
            this.LEmailBuckets1 = new HashSet<LEmailBucket>();
            this.LFinancialSurveys = new HashSet<LFinancialSurvey>();
            this.LFinancialSurveys1 = new HashSet<LFinancialSurvey>();
            this.LFSAnswerBanks = new HashSet<LFSAnswerBank>();
            this.LFSAnswerBanks1 = new HashSet<LFSAnswerBank>();
            this.LFSChapters = new HashSet<LFSChapter>();
            this.LFSChapters1 = new HashSet<LFSChapter>();
            this.LFSNextStepActions = new HashSet<LFSNextStepAction>();
            this.LFSNextStepActions1 = new HashSet<LFSNextStepAction>();
            this.LFSNextSteps = new HashSet<LFSNextStep>();
            this.LFSNextSteps1 = new HashSet<LFSNextStep>();
            this.LFSQuestionBanks = new HashSet<LFSQuestionBank>();
            this.LFSQuestionBanks1 = new HashSet<LFSQuestionBank>();
            this.LFSResponses = new HashSet<LFSRespons>();
            this.LFSResponses1 = new HashSet<LFSRespons>();
            this.LFSSectionItems = new HashSet<LFSSectionItem>();
            this.LFSSectionItems1 = new HashSet<LFSSectionItem>();
            this.LFSSections = new HashSet<LFSSection>();
            this.LFSSections1 = new HashSet<LFSSection>();
            this.LFSSurveyLevels = new HashSet<LFSSurveyLevel>();
            this.LFSSurveyLevels1 = new HashSet<LFSSurveyLevel>();
            this.LLocalPobs = new HashSet<LLocalPob>();
            this.LLocalPobs1 = new HashSet<LLocalPob>();
            this.LLocalPobs2 = new HashSet<LLocalPob>();
            this.LLocalPobs3 = new HashSet<LLocalPob>();
            this.LLocalPobs4 = new HashSet<LLocalPob>();
            this.LLocalPobs5 = new HashSet<LLocalPob>();
            this.LProducts = new HashSet<LProduct>();
            this.LProducts1 = new HashSet<LProduct>();
            this.LProducts2 = new HashSet<LProduct>();
            this.LProducts3 = new HashSet<LProduct>();
            this.LProducts4 = new HashSet<LProduct>();
            this.LProducts5 = new HashSet<LProduct>();
            this.LReconBatches = new HashSet<LReconBatch>();
            this.LReconBatches1 = new HashSet<LReconBatch>();
            this.LReferences = new HashSet<LReference>();
            this.LReferences1 = new HashSet<LReference>();
            this.LReferences2 = new HashSet<LReference>();
            this.LReferences3 = new HashSet<LReference>();
            this.LReferences4 = new HashSet<LReference>();
            this.LReferences5 = new HashSet<LReference>();
            this.LReferenceTypes = new HashSet<LReferenceType>();
            this.LReferenceTypes1 = new HashSet<LReferenceType>();
            this.LRequests = new HashSet<LRequest>();
            this.LRequests1 = new HashSet<LRequest>();
            this.LRequests2 = new HashSet<LRequest>();
            this.LRequests3 = new HashSet<LRequest>();
            this.LRequests4 = new HashSet<LRequest>();
            this.LRequests5 = new HashSet<LRequest>();
            this.LScenarioDemands = new HashSet<LScenarioDemand>();
            this.LScenarioDemands1 = new HashSet<LScenarioDemand>();
            this.LScenarioDemands2 = new HashSet<LScenarioDemand>();
            this.LScenarioDemands3 = new HashSet<LScenarioDemand>();
            this.LScenarioDemands4 = new HashSet<LScenarioDemand>();
            this.LScenarioDemands5 = new HashSet<LScenarioDemand>();
            this.LSupportingDocuments = new HashSet<LSupportingDocument>();
            this.LSupportingDocuments1 = new HashSet<LSupportingDocument>();
            this.LUserActivityLogs = new HashSet<LUserActivityLog>();
            this.LUserActivityLogs1 = new HashSet<LUserActivityLog>();
            this.MLUsersGSecurityQuestions = new HashSet<MLUsersGSecurityQuestion>();
            this.MUserRoles = new HashSet<MUserRole>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string LoginEmail { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Phone { get; set; }
        public bool BlockNotification { get; set; }
        public string Status { get; set; }
        public int CreatedById { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public Nullable<System.DateTime> LockoutUntil { get; set; }
        public string OTP { get; set; }
        public Nullable<System.DateTime> OTPValidUpto { get; set; }
        public Nullable<int> WFOrdinal { get; set; }
        public string WFStatus { get; set; }
        public string WFType { get; set; }
        public string WFComments { get; set; }
        public Nullable<int> WFRequesterId { get; set; }
        public Nullable<int> WFAnalystId { get; set; }
        public Nullable<int> WFManagerId { get; set; }
        public Nullable<int> WFCurrentOwnerId { get; set; }
        public Nullable<int> WFRequesterRoleId { get; set; }
        public bool ChangePwdAtNextLogin { get; set; }
        public Nullable<System.DateTime> WFStatusDateTime { get; set; }
        public Nullable<System.DateTime> WFIsReadyDateTime { get; set; }
        public int Version { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FlexTable> FlexTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCopaDimension> GCopaDimensions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GCopaDimension> GCopaDimensions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GGlobalPob> GGlobalPobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAccountingScenario> LAccountingScenarios5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAudit> LAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEmailBucket> LEmailBuckets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LEmailBucket> LEmailBuckets1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFinancialSurvey> LFinancialSurveys { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFinancialSurvey> LFinancialSurveys1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSAnswerBank> LFSAnswerBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSAnswerBank> LFSAnswerBanks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSChapter> LFSChapters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSChapter> LFSChapters1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSNextStepAction> LFSNextStepActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSNextStepAction> LFSNextStepActions1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSNextStep> LFSNextSteps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSNextStep> LFSNextSteps1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSQuestionBank> LFSQuestionBanks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSQuestionBank> LFSQuestionBanks1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSRespons> LFSResponses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSRespons> LFSResponses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSectionItem> LFSSectionItems { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSectionItem> LFSSectionItems1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSection> LFSSections { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSection> LFSSections1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSurveyLevel> LFSSurveyLevels { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LFSSurveyLevel> LFSSurveyLevels1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LLocalPob> LLocalPobs5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconBatch> LReconBatches { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconBatch> LReconBatches1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReference> LReferences5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReferenceType> LReferenceTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReferenceType> LReferenceTypes1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LRequest> LRequests5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands4 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LScenarioDemand> LScenarioDemands5 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSupportingDocument> LSupportingDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSupportingDocument> LSupportingDocuments1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUserActivityLog> LUserActivityLogs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LUserActivityLog> LUserActivityLogs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MLUsersGSecurityQuestion> MLUsersGSecurityQuestions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MUserRole> MUserRoles { get; set; }
    }
}
