//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LUserActivityLog
    {
        public int Id { get; set; }
        public string Activity { get; set; }
        public string Remarks { get; set; }
        public bool IsActivitySucceeded { get; set; }
        public string HostIP { get; set; }
        public string HostBrowserDetails { get; set; }
        public string HostTimeZone { get; set; }
        public System.DateTime ActivityDateTime { get; set; }
        public string CompanyCode { get; set; }
        public int ActionById { get; set; }
        public int ActionForId { get; set; }
    
        public virtual LUser LUser { get; set; }
        public virtual LUser LUser1 { get; set; }
    }
}
