//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MEntityPortfolio
    {
        public int Id { get; set; }
        public int PortfolioId { get; set; }
        public string EntityType { get; set; }
        public int EntityId { get; set; }
    
        public virtual LPortfolio LPortfolio { get; set; }
    }
}
