//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLFSQuestionBankLFSSurveyLevel
    {
        public int Id { get; set; }
        public int SurveyLevelId { get; set; }
        public string QuestionCode { get; set; }
    
        public virtual LFSSurveyLevel LFSSurveyLevel { get; set; }
    }
}
