//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MLocalGlobalUsecaseMapping
    {
        public int Id { get; set; }
        public int PobCatalogueId { get; set; }
        public int GPobId { get; set; }
        public string UseCaseIndicator { get; set; }
        public System.DateTime EffectiveStartDate { get; set; }
        public System.DateTime EffectiveEndDate { get; set; }
        public string CompanyCode { get; set; }
    
        public virtual GGlobalPob GGlobalPob { get; set; }
    }
}
