//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MStepParticipantActionValidation
    {
        public int Id { get; set; }
        public int StepParticipantActionId { get; set; }
        public int ActionValidationId { get; set; }
        public string SelecterType { get; set; }
    
        public virtual WActionValidation WActionValidation { get; set; }
        public virtual WStepParticipantAction WStepParticipantAction { get; set; }
    }
}
