//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RSysCat
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RSysCat()
        {
            this.LProducts = new HashSet<LProduct>();
            this.LReconBuckets = new HashSet<LReconBucket>();
            this.LReconFileFormats = new HashSet<LReconFileFormat>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public string SysCat { get; set; }
        public int SystemId { get; set; }
        public int CategoryId { get; set; }
        public string SysCatCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LProduct> LProducts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconBucket> LReconBuckets { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LReconFileFormat> LReconFileFormats { get; set; }
        public virtual RProductCategory RProductCategory { get; set; }
        public virtual RProductSystem RProductSystem { get; set; }
    }
}
