//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TReconDataValidation
    {
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int BatchNumber { get; set; }
        public Nullable<int> Ordinal { get; set; }
        public string ProductCode { get; set; }
        public int SysCatId { get; set; }
        public string A001 { get; set; }
        public string A002 { get; set; }
        public string A003 { get; set; }
        public string A004 { get; set; }
        public string A005 { get; set; }
        public string A006 { get; set; }
        public string A007 { get; set; }
        public string A008 { get; set; }
        public string A009 { get; set; }
        public string A010 { get; set; }
        public string A011 { get; set; }
        public string A012 { get; set; }
        public string A013 { get; set; }
        public string A014 { get; set; }
        public string A015 { get; set; }
        public string A016 { get; set; }
        public string A017 { get; set; }
        public string A018 { get; set; }
        public string A019 { get; set; }
        public string A020 { get; set; }
        public string A021 { get; set; }
        public string A022 { get; set; }
        public string A023 { get; set; }
        public string A024 { get; set; }
        public string A025 { get; set; }
        public string A026 { get; set; }
        public string A027 { get; set; }
        public string A028 { get; set; }
        public string A029 { get; set; }
        public string A030 { get; set; }
        public string A031 { get; set; }
        public string A032 { get; set; }
        public string A033 { get; set; }
        public string A034 { get; set; }
        public string A035 { get; set; }
        public string A036 { get; set; }
        public string A037 { get; set; }
        public string A038 { get; set; }
        public string A039 { get; set; }
        public string A040 { get; set; }
        public string A041 { get; set; }
        public string A042 { get; set; }
        public string A043 { get; set; }
        public string A044 { get; set; }
        public string A045 { get; set; }
        public string A046 { get; set; }
        public string A047 { get; set; }
        public string A048 { get; set; }
        public string A049 { get; set; }
        public string A050 { get; set; }
        public string A051 { get; set; }
        public string A052 { get; set; }
        public string A053 { get; set; }
        public string A054 { get; set; }
        public string A055 { get; set; }
        public string A056 { get; set; }
        public string A057 { get; set; }
        public string A058 { get; set; }
        public string A059 { get; set; }
        public string A060 { get; set; }
        public string A061 { get; set; }
        public string A062 { get; set; }
        public string A063 { get; set; }
        public string A064 { get; set; }
        public string A065 { get; set; }
        public string A066 { get; set; }
        public string A067 { get; set; }
        public string A068 { get; set; }
        public string A069 { get; set; }
        public string A070 { get; set; }
        public string A071 { get; set; }
        public string A072 { get; set; }
        public string A073 { get; set; }
        public string A074 { get; set; }
        public string A075 { get; set; }
        public string A076 { get; set; }
        public string A077 { get; set; }
        public string A078 { get; set; }
        public string A079 { get; set; }
        public string A080 { get; set; }
        public string A081 { get; set; }
        public string A082 { get; set; }
        public string A083 { get; set; }
        public string A084 { get; set; }
        public string A085 { get; set; }
        public string A086 { get; set; }
        public string A087 { get; set; }
        public string A088 { get; set; }
        public string A089 { get; set; }
        public string A090 { get; set; }
        public string A091 { get; set; }
        public string A092 { get; set; }
        public string A093 { get; set; }
        public string A094 { get; set; }
        public string A095 { get; set; }
        public string A096 { get; set; }
        public string A097 { get; set; }
        public string A098 { get; set; }
        public string A099 { get; set; }
        public string A100 { get; set; }
        public string ValidationMessage { get; set; }
        public Nullable<int> SrNo { get; set; }
    }
}
