//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRefDataValidation
    {
        public int Id { get; set; }
        public int ReferenceId { get; set; }
        public Nullable<System.DateTime> EffectiveStartDate { get; set; }
        public Nullable<System.DateTime> EffectiveEndDate { get; set; }
        public Nullable<int> CreatedById { get; set; }
        public System.DateTime CreatedDateTime { get; set; }
        public int UpdatedById { get; set; }
        public System.DateTime UpdatedDateTime { get; set; }
        public string AttributeC01 { get; set; }
        public string AttributeC02 { get; set; }
        public string AttributeC03 { get; set; }
        public string AttributeC04 { get; set; }
        public string AttributeC05 { get; set; }
        public string AttributeC06 { get; set; }
        public string AttributeC07 { get; set; }
        public string AttributeC08 { get; set; }
        public string AttributeC09 { get; set; }
        public string AttributeC10 { get; set; }
        public string AttributeC11 { get; set; }
        public string AttributeC12 { get; set; }
        public string AttributeC13 { get; set; }
        public string AttributeC14 { get; set; }
        public string AttributeC15 { get; set; }
        public string AttributeC16 { get; set; }
        public string AttributeC17 { get; set; }
        public string AttributeC18 { get; set; }
        public string AttributeC19 { get; set; }
        public string AttributeC20 { get; set; }
        public string AttributeM01 { get; set; }
        public string AttributeM02 { get; set; }
        public string AttributeM03 { get; set; }
        public string AttributeM04 { get; set; }
        public string AttributeM05 { get; set; }
        public string AttributeN01 { get; set; }
        public string AttributeN02 { get; set; }
        public string AttributeN03 { get; set; }
        public string AttributeN04 { get; set; }
        public string AttributeN05 { get; set; }
        public string AttributeN06 { get; set; }
        public string AttributeN07 { get; set; }
        public string AttributeN08 { get; set; }
        public string AttributeN09 { get; set; }
        public string AttributeN10 { get; set; }
        public string AttributeI01 { get; set; }
        public string AttributeI02 { get; set; }
        public string AttributeI03 { get; set; }
        public string AttributeI04 { get; set; }
        public string AttributeI05 { get; set; }
        public string AttributeI06 { get; set; }
        public string AttributeI07 { get; set; }
        public string AttributeI08 { get; set; }
        public string AttributeI09 { get; set; }
        public string AttributeI10 { get; set; }
        public string AttributeD01 { get; set; }
        public string AttributeD02 { get; set; }
        public string AttributeD03 { get; set; }
        public string AttributeD04 { get; set; }
        public string AttributeD05 { get; set; }
        public string AttributeD06 { get; set; }
        public string AttributeD07 { get; set; }
        public string AttributeD08 { get; set; }
        public string AttributeD09 { get; set; }
        public string AttributeD10 { get; set; }
        public string AttributeB01 { get; set; }
        public string AttributeB02 { get; set; }
        public string AttributeB03 { get; set; }
        public string AttributeB04 { get; set; }
        public string AttributeB05 { get; set; }
        public string AttributeB06 { get; set; }
        public string AttributeB07 { get; set; }
        public string AttributeB08 { get; set; }
        public string AttributeB09 { get; set; }
        public string AttributeB10 { get; set; }
        public Nullable<int> UserId { get; set; }
        public string ValidationMessage { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public Nullable<int> SrNo { get; set; }
    }
}
