//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WActionValidation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WActionValidation()
        {
            this.MStepParticipantActionValidations = new HashSet<MStepParticipantActionValidation>();
        }
    
        public int Id { get; set; }
        public string ValidationName { get; set; }
        public string Description { get; set; }
        public string ValidationMessage { get; set; }
        public bool IsShowStopper { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MStepParticipantActionValidation> MStepParticipantActionValidations { get; set; }
    }
}
