//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WStepParticipantAction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WStepParticipantAction()
        {
            this.MStepParticipantActionValidations = new HashSet<MStepParticipantActionValidation>();
        }
    
        public int Id { get; set; }
        public int WActionId { get; set; }
        public string Label { get; set; }
        public string Glymph { get; set; }
        public int ShowInStepId { get; set; }
        public bool ButtonOnWfGrid { get; set; }
        public bool ButtonOnForm { get; set; }
        public string VisibilityFunction { get; set; }
        public int ParticipantId { get; set; }
        public string ParticipantType { get; set; }
        public string Description { get; set; }
        public bool IsLinkOverWFGrid { get; set; }
        public Nullable<int> SendToStepId { get; set; }
        public string ActionUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MStepParticipantActionValidation> MStepParticipantActionValidations { get; set; }
        public virtual WStep WStep { get; set; }
    }
}
