//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WStep
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WStep()
        {
            this.LAudits = new HashSet<LAudit>();
            this.LNotifications = new HashSet<LNotification>();
            this.LSupportingDocuments = new HashSet<LSupportingDocument>();
            this.WStepGridColumns = new HashSet<WStepGridColumn>();
            this.WStepParticipantActions = new HashSet<WStepParticipantAction>();
            this.WStepParticipants = new HashSet<WStepParticipant>();
        }
    
        public int Id { get; set; }
        public string CompanyCode { get; set; }
        public int WorkFlowId { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Label { get; set; }
        public int Ordinal { get; set; }
        public bool Skip { get; set; }
        public string SkipFunctionName { get; set; }
        public string Banner { get; set; }
        public bool DoNotNotify { get; set; }
        public bool IsReady { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LAudit> LAudits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LNotification> LNotifications { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LSupportingDocument> LSupportingDocuments { get; set; }
        public virtual RWorkFlow RWorkFlow { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WStepGridColumn> WStepGridColumns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WStepParticipantAction> WStepParticipantActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WStepParticipant> WStepParticipants { get; set; }
    }
}
