//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WStepGridColumn
    {
        public int Id { get; set; }
        public int WStepId { get; set; }
        public string ColumnName { get; set; }
        public string Label { get; set; }
        public bool ShouldBeVisible { get; set; }
        public Nullable<int> OrderByOrdinal { get; set; }
        public string AscDesc { get; set; }
        public int Ordinal { get; set; }
        public string FunctionName { get; set; }
        public string JoinTable { get; set; }
        public string JoinTableColumn { get; set; }
        public string BaseTableJoinColumn { get; set; }
    
        public virtual WStep WStep { get; set; }
    }
}
