//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XBatch
    {
        public int Id { get; set; }
        public string XCompanyCode { get; set; }
        public string XUpdatedBy { get; set; }
        public int XBatchNumber { get; set; }
        public string XBatchType { get; set; }
        public string XRawDataType { get; set; }
        public string XStatus { get; set; }
        public System.DateTime XUploadStartDateTime { get; set; }
        public Nullable<System.DateTime> XUploadFinishDateTime { get; set; }
        public Nullable<int> XRecordCount { get; set; }
        public Nullable<int> XAlteryxBatchNumber { get; set; }
        public string XComments { get; set; }
        public string BatchName { get; set; }
    }
}
