//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RELY_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class XRequestUpload
    {
        public int Id { get; set; }
        public string XCompanyId { get; set; }
        public string XProductId { get; set; }
        public string XAutherzationNumber { get; set; }
        public string XFileNames { get; set; }
        public string XUserFriendlyFileNames { get; set; }
        public string XSegment { get; set; }
        public string XGate { get; set; }
        public string XSystem { get; set; }
        public string XSurvey { get; set; }
        public string XBusinessCategory { get; set; }
        public string XS15impact { get; set; }
        public string XSupportedbyExistingSystems { get; set; }
        public string XTypeofProduct { get; set; }
        public string XCreateNewLocalPOBName { get; set; }
        public string XGlobalPOB1Acquisit { get; set; }
        public string XGlobalPOB2Retention { get; set; }
        public string XCopaDimesionCallOriginDestination { get; set; }
        public string XCopaDimesionBearerTechnology { get; set; }
        public string XBatchNumber { get; set; }
        public Nullable<System.DateTime> XCreatedDateTime { get; set; }
        public Nullable<System.DateTime> XUpdatedDateTime { get; set; }
        public Nullable<decimal> XSspAmount { get; set; }
        public string XSpecialIndicator { get; set; }
        public string Action { get; set; }
        public string XPOBIndicator { get; set; }
        public string XUsageIndicator { get; set; }
        public string XBundleIndicator { get; set; }
        public string XArticleNumber { get; set; }
    }
}
